

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Button;
                ref class Slider;
                ref class ToggleSwitch;
                ref class StackPanel;
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                namespace Primitives {
                    ref class Popup;
                }
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace GameEngine
{
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::SwapChainBackgroundPanel, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ GamePlayGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ MenuButtonsGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ LevelButtonsGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ PausedScreen;
        private: ::Windows::UI::Xaml::Controls::Primitives::Popup^ stkMusicSfx;
        private: ::Windows::UI::Xaml::Controls::Primitives::Popup^ popupPaused;
        private: ::Windows::UI::Xaml::Controls::Primitives::Popup^ popupPrivacy;
        private: ::Windows::UI::Xaml::Controls::Primitives::Popup^ popupAbout;
        private: ::Windows::UI::Xaml::Controls::Grid^ grdAbout;
        private: ::Windows::UI::Xaml::Controls::Button^ dismissAbout;
        private: ::Windows::UI::Xaml::Controls::Grid^ grdPrivacy;
        private: ::Windows::UI::Xaml::Controls::Button^ dismissPrivacy;
        private: ::Windows::UI::Xaml::Controls::Grid^ grdPaused;
        private: ::Windows::UI::Xaml::Controls::Button^ UnpauseButton;
        private: ::Windows::UI::Xaml::Controls::Button^ Quit;
        private: ::Windows::UI::Xaml::Controls::Button^ SettingsBut;
        private: ::Windows::UI::Xaml::Controls::Button^ dismissPaused;
        private: ::Windows::UI::Xaml::Controls::Grid^ grdSubMusicSfx;
        private: ::Windows::UI::Xaml::Controls::Slider^ sldSFXVolume;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ tglSFX;
        private: ::Windows::UI::Xaml::Controls::Slider^ sldMusicVolume;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ tglMusic;
        private: ::Windows::UI::Xaml::Controls::Button^ dismissAudioSettings;
        private: ::Windows::UI::Xaml::Controls::Button^ backToMenu;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ LevelsPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ ButtonsPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ HighScoresPanel;
        private: ::Windows::UI::Xaml::Controls::Button^ PlayButton;
        private: ::Windows::UI::Xaml::Controls::Button^ ShareButton;
        private: ::Windows::UI::Xaml::Controls::Grid^ HUD;
        private: ::Windows::UI::Xaml::Controls::Button^ ShootButton;
        private: ::Windows::UI::Xaml::Controls::Button^ PauseButton;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ HealthBar;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Score;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Clock;
    };
}

